name: Paren Checker Test

on:
  pull-request:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      working-directory: .

    strategy:
      matrix:
        python-version: [3.8,3.10]

    env:
      MODE: "dev" 

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Test python code
        run: 'python ./test_parenCheck.py'
